CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE IF NOT EXISTS coastal_prices (
	id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
	month TEXT NOT NULL UNIQUE,
	_95_lrp DOUBLE PRECISION DEFAULT NULL,
	_95_ulp DOUBLE PRECISION DEFAULT NULL,
	diesel_005 DOUBLE PRECISION DEFAULT NULL,
	diesel_0005 DOUBLE PRECISION DEFAULT NULL,
	illuminating_paraffin DOUBLE PRECISION DEFAULT NULL,
	liquefied_petroleum_gas DOUBLE PRECISION DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS inland_prices (
	id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
	month TEXT NOT NULL UNIQUE,
	_93_lrp DOUBLE PRECISION DEFAULT NULL,
	_93_ulp DOUBLE PRECISION DEFAULT NULL,
	_95_ulp DOUBLE PRECISION DEFAULT NULL,
	diesel_005 DOUBLE PRECISION DEFAULT NULL,
	diesel_0005 DOUBLE PRECISION DEFAULT NULL,
	illuminating_paraffin DOUBLE PRECISION DEFAULT NULL,
	liquefied_petroleum_gas DOUBLE PRECISION DEFAULT NULL
);
